version: '3.8'
services:
  ### ===================
  ### KEYCLOAK
  ### ===================
  keycloak:
      container_name: keycloak
      hostname: keycloak
      image: quay.io/keycloak/keycloak:25.0
      command: start
      environment:
        KC_HOSTNAME: localhost
        KC_HOSTNAME_PORT: 8080
        KC_HOSTNAME_STRICT_BACKCHANNEL: false
        KC_HTTP_ENABLED: true
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
        KEYCLOAK_ADMIN: brook
        KEYCLOAK_ADMIN_PASSWORD: kmzway87aa
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
        KC_DB_USERNAME: keycloak_db_user
        KC_DB_PASSWORD: keycloak_db_user_password
      ports:
        - 8081:8080
      restart: always
      volumes:
        - ./config/realm.json:/opt/keycloak/data/import/realm.json:ro
      networks:
        - micro-service-network
### ===================================
### NETWORKS GROUP FOR ONE SAME SERVICE
### ===================================
networks:
  micro-service-network:
    external: true