version: "3.8"
services:
  ### ===================
  ### APISIX
  ### ===================
  apisix:
    container_name: apisix
    hostname: apisix
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.9.0-debian}
    restart: always
    volumes:
      - ./config/apisix.yml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - 9180:9180
      - 9080:9080
      - 9091:9091
      - 9443:9443
      - 9092:9092
    networks:
      micro-service-network:
  ### ===================
  ### UPSTREAM
  ### ===================
  web1:
    container_name: web1
    hostname: web1
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./config/upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      micro-service-network:
  web2:
    container_name: web2
    hostname: web2
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./config/upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      micro-service-network:
  ### ===================
  ### DASHBOARD
  ### ===================
  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: apache/apisix-dashboard
    restart: always
    volumes:
      - ./config/dashboard.yml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - apisix
    ports:
        - "9000:9000"
    networks:
        micro-service-network:
### ===================================
### NETWORKS GROUP FOR ONE SAME SERVICE
### ===================================
networks:
  micro-service-network:
    external: true